# Auto-generated by Install.ps1 ? edit $claudePath / $logFile to customise
$claudePath = (Get-Command claude -ErrorAction SilentlyContinue).Source
if (-not $claudePath) { $claudePath = "
C:\Users\aj\AppData\Roaming\npm\claude.cmd
" }
$logFile    = "
C:\Users\aj\ClaudeAnchors
\logs\
W4-Backup
.log"
$timestamp  = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
"=== $timestamp ===" | Out-File -FilePath $logFile -Append -Encoding UTF8
$prompt = "Window 
4
 open $([char]0x2014) 
8pm
 block. Reply OK only."
& $claudePath -p $prompt 2>&1 | Out-File -FilePath $logFile -Append -Encoding UTF8
